---
title: Conflito e negociação
subtitle: Comportamento Organizacional
author:
  - name: 
      given: Luis F.
      family: Gómez L.
    orcid: 0000-0002-2877-9015
    email: luis.gomezl@unimilitar.edu.co
    affiliations:
      - name: Faculdade de Educação a Distância
toc: true
toc-depth: 1
slide-level: 2
format:
  presentation-umng-revealjs:
    logo-vertical-strip: 000_logos/logo-white-vertical.png 
    embed-resources: true
    reference-location: document
    mermaid-format: png
    output-file: index.html
date: last-modified
date-format: "D MMMM, YYYY"
knitr: 
  opts_chunk: 
    echo: false
    warning: false
    fig.align: center
    out.width: 85%
lang: pt
bibliography: ifpe-umng.bib
csl: apa.csl
editor: source
---

# O que fazem os administradores?

## 

```{mermaid}
%%| label: fig-management-functions
%%| fig-cap: Funções dos administradores [@robbins_organizational_2024, p. 40]
%%| fig-height: 5

flowchart TB
    A("`Funções`")  --> A1("`Planejar`") --> A11("`Definir metas, estabelecer uma estratégia e desenvolver planos para coordenar atividades.`")
    A --> A2("`Organizar`") --> A21("`Determinar quais tarefas devem ser realizadas, quem as executa, como as tarefas são agrupadas, quem se reporta a quem e onde são tomadas as decisões.`")
    A --> A3("`Dirigir`") --> A31("`Motivar os empregados, dirigir outras pessoas, escolher os canais de comunicação mais eficazes e **resolver conflitos**.`")
    A --> A4("`Controlar`") --> A41("`Supervisionar as atividades para assegurar que sejam cumpridas conforme o planejado e corrigir os desvios importantes.`")

    classDef UmngNode fill:#fdc600,stroke:#043074,stroke-width:2px;
    class A,A1,A11,A2,A21,A3,A31,A4,A41 UmngNode;
```

## 

```{mermaid}
%%| label: fig-manager-roles
%%| fig-cap: Papéis dos administradores segundo Mintzberg [@robbins_organizational_2024, pp. 41-42]
%%| fig-height: 5

flowchart TB
    A("`Papéis`") --> A1(Informacionais)
    A1 --> A11("`Monitor
    Líder
    Porta-voz`")
    A --> A2(Interpessoais)
    A2 --> A21("`Símbolo
    Líder
    Ligação`")
    A --> A3(Decisórios)
    A3 --> A31("`Empreendedor
    **Solucionador de conflitos**
    Alocador de recursos
    **Negociador**`")

    classDef UmngNode fill:#fdc600,stroke:#043074,stroke-width:2px;
    class A,A1,A11,A2,A21,A3,A31,A4,A41 UmngNode;
```

# Modelo Básico do Comportamento Organizacional

##

```{mermaid}
%%| label: fig-bo-model
%%| fig-cap: Modelo Básico do Comportamento Organizacional [@robbins_organizational_2024, p. 61]
%%| fig-height: 5
flowchart TB
    subgraph S3["`**Resultados**`"]
      C1(Individual) 
      C2("`**Grupal**
      Desempenho da equipe`") 
      C3(Organizacional)
    end
    
    subgraph S2["`**Processos**`"]
      B1(Individual) 
      B2("`**Grupal**
      Comunicação
      Liderança
      Poder e políticas
      **Conflito e negociação**`") 
      B3(Organizacional)
    end
    
    subgraph S1["`**Insumos**`"]
      A1(Individual) 
      A2("`**Grupal**
      Estrutura
      Papéis
      Responsabilidade da equipe`") 
      A3(Organizacional)
    end

    classDef UmngNode fill:#fdc600,stroke:#043074,stroke-width:2px;
    class A1,A2,A3,B1,B2,B3,C1,C2,C3 UmngNode;
    
    style S1 fill:#16a085,stroke:#043074,stroke-width:2px
    style S2 fill:#16a085,stroke:#043074,stroke-width:2px
    style S3 fill:#16a085,stroke:#043074,stroke-width:2px
```

# Conflito

## {.center}

::: {#def-conflict}

## Conflito

O conflito é uma manifestação entre pelo menos duas partes interdependentes que percebem objetivos incompatíveis e a interferência de outros no alcance de seus objetivos. [@hocker_interpersonal_2018, p. 3]

:::

##

```{mermaid}
%%| label: fig-conflict-types
%%| fig-cap: Tipos de conflitos [@robbins_organizational_2024, pp. 479-481]
%%| fig-height: 5

flowchart LR
    A("`Tipos`")  --> A1("`Relacionamento`") --> A11("`Relações interpessoais`") ---> A111("`Disfuncional`")
    A --> A2("`Tarefa`") --> A21("`Conteúdo e objetivos do trabalho`") ---> A211("`**Funcional ou disfuncional?**`")
    A --> A3("`Processo`")--> A31("`Maneira como o trabalho é realizado`") ---> A311("`Disfuncional`")

    classDef UmngNode fill:#fdc600,stroke:#043074,stroke-width:2px;
    class A,A1,A11,A111,A2,A21,A211,A3,A31,A311 UmngNode;
```

##



# Negociação 

## {.center}

::: {#def-negotiation}

## Negociação

A negociação é um processo de tomada de decisão em que duas ou mais partes conversam entre si em um esforço para resolver seus interesses opostos [@lewicki_negotiation_2024, p. 3].

:::

# Simulação

## {.smaller .center}

- **Instruções da simulação**

    - *Objetivo a negociar*

        - Cada estudante pode escolher entre duas opções para aumentar sua nota final:

            - Opção A: aumentar 0,5 pontos
            - Opção B: aumentar 1 ponto

        - *Condição*:

          - Se mais de 10% da turma escolher a Opção B, nenhum estudante receberá pontos adicionais.
          - Se 10% ou menos escolherem a Opção B, cada estudante receberá o aumento correspondente à opção escolhida.

          Portanto, os estudantes devem negociar coletivamente como proceder.

## {.smaller .center}

- *Etapa 1 – Negociação coletiva*

    - A turma terá um tempo limitado para conversar e se coordenar.

    - Podem discutir estratégias, acordos ou compromissos comuns.

- *Etapa 2 – Decisão individual e anônima*

    - Após a negociação, cada estudante escolherá de forma individual e secreta entre a Opção A ou a Opção B.

    - Todas as respostas serão recolhidas de maneira anônima.

    - Uma vez recolhidas, o resultado final será calculado e comunicado a toda a turma.
    
## {background-image="000_images/fig-bird-umng-1.jpg"}

::: {.r-fit-text}

Obrigado

:::

# Referências {.allowbreaks}